
DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER(
	ID VARCHAR2(500) PRIMARY KEY,
	PASSWORD VARCHAR2(500) NOT NULL,
	NAME VARCHAR2(500) NOT NULL
);

INSERT INTO CUSTOMER VALUES('admin2', 'admin1234', '관리자');

SELECT * FROM CUSTOMER;
