
DROP SEQUENCE MYMVCBOARDSEQ;
DROP TABLE MYMVCBOARD;

CREATE SEQUENCE MYMVCBOARDSEQ;

CREATE TABLE MYMVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
)

INSERT INTO MYMVCBOARD(SEQ, WRITER, TITLE, CONTENT, REGDATE)
VALUES(MYMVCBOARDSEQ.NEXTVAL, '관리자', 'TEST', 'TEST중입니다', SYSDATE);

SELECT * FROM MYMVCBOARD;


